name: Code Check Pipeline
# This is responsible for checking code guidelines with Detekt & Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  code_analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: |
          ./gradlew --console=plain detekt --stacktrace
#      - name: Upload Detekt reports
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: detekt
#          path: ./build/reports/detekt